<div class="container-about">
    <header>
        <h1>À Propos</h1>
    </header>
    
    <section class="app-concept">
        <h2>Concept</h2>
        <p>
            Application permettant de discuter de manière totalement anonyme
            dans différents salons. Il n'est donc pas nécessaire de créer de compte.
            Ces salons peuvent être crées soit par d'autres personnes soit par vous-même
            si le sujet principal du salon ne correspond pas à ce que vous recherchez. 
        </p>
    </section>
    
    <section class="app-features">
        <h2>Fonctionnalités clés</h2>
        <ul>
            <li>Création de salons</li>
            <li>Affichage de la liste des salons</li>
            <li>Navigation entre salons possibles</li>
            <li>Mise en évidence du salon actif</li>
            <li>Envoi de messages possibles dans le salon actif</li>
            <li>Affichage des messages du salon actif triés par date et heure d'envoi</li>
            <li>Possibilité d'épingler un seul message par salon</li>
        </ul>
    </section>
    
    <section class="app-technologies">
        <h2>Technlogoies utilisées </h2>
        <p>Projet réalisé en HTML et CSS ainsi que MySQL et PHP côté back-end</p>
    </section>
</div>